### PR TITLE
clickhouse: extract the path of remote files 

### PR DESCRIPTION
**Pull request by kmichel-aiven**
After collecting metadata files of files in object storage, extract
the path of the remote files.

This required an extension of the snapshot protocol to have
different option for each glob.

### CODE REVIEW

**Comment by kmichel-aiven** [comment]
To be rebased after #117 is merged.

**Review by alanfranz — APPROVED** [review]
LGTM, but I'm probably not the best person to understand the whole context and all the details. If nobody else is reviewing this, ping me next Monday and I'll try to do a more thorough review+merge.

**Comment by aris-aiven** [comment]
Planning to do a review as well for sure

**Review by aris-aiven — APPROVED** [review]
LGTM as well

**Pull request merged**
