### PR TITLE
Use Rohmu models directly

### PR DESCRIPTION
**Pull request by joelynch**
Some types were added to help with some debugging I was doing.

### CODE REVIEW

**Comment by joelynch** [comment]
There might be some issues with this and `notifier` as discussed in the rohmu PR.

**Review by fingon — APPROVED** [review]
Otherwise this LGTM but I don't know about the clickhouse, and more specifically the string->bytes changes there. @kmichel-aiven ?

**Comment by joelynch** [comment]
VSCode had red underlined them all but since Table is a pydantic model it converts str to bytes automatically so I didn't really need to make that change and can revert

**Review by kmichel-aiven — APPROVED** [review]
LGTM, the changes to bytes are correct too.

**Pull request merged**
