### PR TITLE
Update python to 3.11 and fix the test suite

### PR DESCRIPTION
**Pull request by aris-aiven**
This is a follow up of #93 focusing on test suite breakage ensuing the fastapi requirement update.

### CODE REVIEW

**Comment by aris-aiven** [comment]
I was optimistic the test suite would pass for 3.11 but was running it in a 3.10 venv.. Do not feel obliged to review.

**Review by fingon — CHANGES_REQUESTED** [review]
Marking changes requested to hide it in my filter - did not review - please ask for review next time when tests pass ;-)

**Comment by mhoffm-aiven** [comment]
Quick observation:
on fedora 37
```POST /node/LockCall.lock?locker=locker&ttl=60```
on fedora 35
```POST /node/lock?locker=locker&ttl=60```

the "LockCall" Enum needs a `__str__` method probably

**Review by mhoffm-aiven — APPROVED** [review]
lgtm

**Comment by aris-aiven** [comment]
``podman-test`` passes on both f35 and f37 (with the addition of ``python3-snappy`` build dependency due to https://github.com/andrix/python-snappy/issues/124)

**Pull request merged**
